sudo: required

services:
  - docker

language: go

before_install:
  # installing newer docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # installing the faas-cli
  - curl -sSL https://cli.openfaas.com | sudo sh
  - docker swarm init
  - ./ci-setup.sh

script:
  - go test $(go list ./... | grep -v /vendor/) -race -coverprofile=coverage.txt -covermode=atomic

after_script:
  - docker swarm leave -f

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    faas-cli push -f stack.yml;
    fi
