provider:
  name: faas
  gateway: http://localhost:8080

functions:
  primitive:
    lang: go
    handler: ./function
    image: diddledan/primitive
    environment:
      read_timeout: 60
      write_timeout: 60
      content_type: image/svg+xml
      PRIMITIVE_COUNT: 10
